python MainCalculations_LCDfrequency.py
python MainCalculations_LCDfrequency.py -s
python Calculate_OrganismLevel_PrimaryLCDfrequencies.py
python Calculate_OrganismLevel_LCDfrequencyMatrices.py
python plot_OrganismLevel_LCDclassRarity_CategoricalHeatmaps.py
python plot_Percentage_Organisms_with_PrimaryLCD.py
python plot_OrganismLevel_SecondaryLCDfrequencies_Heatmaps.py
python get_ModelOrganism_CrichLCDs.py
python run_GOanalyses_ModelOrganisms_CrichLCDprots.py
python get_ModelOrganisms_KeratinAssociated_CrichSubset.py
python plot_UpSet_ModelOrganisms_KeratinAssociated_CrichSubset.py
python plot_KeratinProtein_DomainLayout.py
python Analyze_PfamClans_LCDclasses.py
python plot_PfamClan_Statistics_AllOrganisms.py
python plot_PfamClanData_Humans.py
python Categorize_LCDclasses_Rare_SemiRare_Common.py
python calculate_ProteinLevelStatistics_EukaryoteSpecificLCDclasses.py
python plot_EukaryoteSpecific_LCDclassStatistics.py
python run_GOanalyses_XXprots.py -c HQ
python run_GOanalyses_XXprots.py -c HL
python run_GOanalyses_XXprots.py -c NH
python run_GOanalyses_XXprots.py -c NM
python gather_HL_NH_NM_GOterm_Results.py
python get_HQprot_NonOverlapping_QX-XQ-HX-XH_LCD_proteins.py
python get_HQprot_NonOverlapping_QrichPrimaryLCD_proteins.py
python run_GOanalyses_HQprots_Exclude_QX-XQ-HX-XH_Proteins.py
python run_GOanalyses_HQprots_Exclude_QrichPrimaryLCD_Proteins.py
python plot_HQ_GOterm_Results.py
python get_Top3organisms_with_Highest_PerResidueOccupancy.py
python make_PerResidueLevel_Matrices.py
python plot_Top3organisms_PrimaryLCD_PerResidueOccupancy_Barplots.py
python plot_PerResidueLCDoccupancy_SecondaryLCD_Heatmaps.py
python plot_PieChart_Organisms_with_Most_LCDclasses_PerResiduesLevelStatistics.py
python plot_LetterMaps_TopOrganisms_Eukaryota.py
python plot_LetterMaps_TopOrganisms_ArchaeaBacteriaViruses.py
python compare_proteomes_PerResidueLCDoccupancy.py
python compare_Observed_vs_Scrambled_Frequencies.py
python Plot_PercentOfOrganisms_with_Enriched_or_Depleted_LCDs.py
python Plot_Median_lnOR_AcrossOrganisms_by_LCDclass.py
python calculate_BackgroundAAfrequencies_AllProteomes.py
python plot_IndividualOrganism_lnORs_and_Pvals.py
python plot_Mean_ShareOfSecondaryLCDs_devoted_to_EachLCDclass_DOMAIN_OF_LIFE.py
python plot_ShareOfSecondaryLCDs_devoted_to_EachLCDclass_SINGLE_ORGANISM.py