python MainCalculations_LCDfrequency.py
python MainCalculations_LCDfrequency.py -s
python Calculate_OrganismLevel_PrimaryLCDfrequencies.py
python Calculate_OrganismLevel_LCDfrequencyMatrices.py
python plot_OrganismLevel_LCDclassRarity_CategoricalHeatmaps.py
python plot_Percentage_Organisms_with_PrimaryLCD.py
python plot_OrganismLevel_SecondaryLCDfrequencies_Heatmaps.py
python get_ModelOrganisms_KeratinAssociated_CrichSubset.py
python plot_UpSet_ModelOrganisms_KeratinAssociated_CrichSubset.py
python plot_KeratinProtein_DomainLayout.py
python Analyze_PfamClans_LCDclasses.py
python plot_PfamClan_Statistics_AllOrganisms.py
python plot_PfamClanData_Humans.py
python Categorize_LCDclasses_Rare_SemiRare_Common.py
python calculate_ProteinLevelStatistics_EukaryoteSpecificLCDclasses.py
python plot_EukaryoteSpecific_LCDclassStatistics.py
python write_GOanalysis_BatchFiles.py
.\Run_Archaea_GOanalyses.bat
.\Run_Bacteria_GOanalyses.bat
.\Run_Eukaryota_GOanalyses.bat
.\Run_Viruses_GOanalyses.bat
python analyze_GOresults.py
python plot_TopRanking_GOterms_DomainsOfLife.py
python get_HQprot_NonOverlapping_QX-XQ-HX-XH_LCD_proteins.py
python get_HQprot_NonOverlapping_QrichPrimaryLCD_proteins.py
python get_HQprot_NonOverlapping_HrichPrimaryLCD_proteins.py
python make_BatchFile_GOanalyses_QX-XQ-HX-XH_prots_excluded.py
python make_BatchFile_GOanalyses_QrichPrimary_prots_excluded.py
python make_BatchFile_GOanalyses_HrichPrimary_prots_excluded.py
.\RUN_Eukaryotes_HQprots_with_HrichPrimary_Excluded.bat
.\RUN_Eukaryotes_HQprots_with_QrichPrimary_Excluded.bat
.\RUN_Eukaryotes_HQprots_with_QX-XQ-HX-XH_LCDs_Excluded.bat
python run_GOanalyses_by_Eukaryotes_QX-XQ-HX-XH_excluded.py
python run_GOanalyses_by_Eukaryotes_QrichPrimary_excluded.py
python run_GOanalyses_by_Eukaryotes_HrichPrimary_excluded.py
python analyze_GOresults_HQprots_Only.py
python plot_HQ_GOterm_Results.py
python plot_GOresults_SpecificLCDclasses.py
python plot_CX-LCDs_GOterm_Results_MammalsOnly.py
python plot_HL-NH-NM_GOresults_Eukaryotes.py
python get_Top3organisms_with_Highest_PerResidueOccupancy.py
python make_PerResidueLevel_Matrices.py
python plot_Top3organisms_PrimaryLCD_PerResidueOccupancy_Barplots.py
python plot_PerResidueLCDoccupancy_SecondaryLCD_Heatmaps.py
python plot_PieChart_Organisms_with_Most_LCDclasses_PerResiduesLevelStatistics.py
python plot_LetterMaps_TopOrganisms_Eukaryota.py
python plot_LetterMaps_TopOrganisms_ArchaeaBacteriaViruses.py
python compare_proteomes_PerResidueLCDoccupancy.py
python compare_Observed_vs_Scrambled_Frequencies.py
python Plot_PercentOfOrganisms_with_Enriched_or_Depleted_LCDs.py
python Plot_Median_lnOR_AcrossOrganisms_by_LCDclass.py
python calculate_BackgroundAAfrequencies_AllProteomes.py
python plot_IndividualOrganism_lnORs_and_Pvals.py
python plot_Mean_ShareOfSecondaryLCDs_devoted_to_EachLCDclass_DOMAIN_OF_LIFE.py
python plot_ShareOfSecondaryLCDs_devoted_to_EachLCDclass_SINGLE_ORGANISM.py
python gather_VariedParam_LCDdata.py
python construct_VariedParam_Matrices.py
python plot_VariedWindowSize_Heatmaps.py
python plot_VariedCompThresholds_Heatmaps.py
python gather_VariedParam_LCDdata_PerResidueLCDoccupancies.py
python construct_VariedParam_Matrices_PerResidueOccupancies.py
python plot_VariedWindowSize_PerResidueOccupancies_Heatmaps.py
python plot_VariedCompThresholds_PerResidueOccupancies_Heatmaps.py
python plot_mean_PerResidueOccupancy_matrix_AllOrganisms_Categorical.py
python plot_OrganismLevel_LCDfrequency_BasicClades.py
python calculate_Pairwise_ManhattanDistance.py
python plot_MeanPairwiseDistances_Clustermaps.py